### ISSUE TITLE
something about the dataset

### ISSUE THREAD

**Issue by chenchouyu** [TwistedW/MIAV#4]
Congratulations on the publication of your paper. However, in this project, I can't find the 100 fundus images with A/V annotations promised to be published in the article. Could you tell me where I can access them? Thanks

**Comment by TwistedW** [comment]
@chenchouyu The 100 fundus images dataset has been released.You can get it in ReadMe.

[Open_BUA_AV](https://pan.baidu.com/s/1V0eChuEa6_ec0lVtP7Nu1w )

Password：00di

I've been a little busy recently and have been forgetting to update, thank you for reminding me.
